# Generated by Django 4.1.5 on 2023-01-13 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250)),
                ('branch_id', models.IntegerField(blank=True, default=0)),
                ('address', models.CharField(blank=True, max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Branches',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, default=0)),
                ('user_firstname', models.CharField(blank=True, max_length=256, null=True, verbose_name='firstname')),
                ('user_lastname', models.IntegerField(blank=True, default=0)),
                ('issue_date', models.DateTimeField(blank=True)),
                ('expiry_date', models.DateTimeField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='data/certificates/', verbose_name='Files')),
                ('active_time', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Certificates',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250)),
                ('code', models.IntegerField(blank=True, default=0)),
            ],
            options={
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=256, null=True, verbose_name='firstname')),
                ('lastname', models.CharField(blank=True, max_length=256, null=True, verbose_name='lastname')),
                ('permission', models.BooleanField(default=False)),
                ('email', models.EmailField(blank=True, default='', max_length=250, verbose_name='email')),
                ('contact', models.CharField(blank=True, default='', max_length=250, verbose_name='contact')),
                ('position', models.CharField(blank=True, default='', max_length=250, verbose_name='position')),
                ('status', models.CharField(choices=[('null', "Noma'lum"), ('0', 'Admin')], default='null', max_length=10, verbose_name='Nomalum')),
                ('live', models.CharField(choices=[('0', 'Faol emas'), ('1', 'Faol')], default='0', max_length=10, verbose_name='faol')),
                ('active_time', models.DateTimeField(auto_now=True, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workerbranch', to='index.branch')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workerdepartment', to='index.department')),
                ('user', models.OneToOneField(help_text='User linked to this profile', on_delete=django.db.models.deletion.PROTECT, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Related user')),
            ],
            options={
                'verbose_name': 'Worker',
                'verbose_name_plural': 'Workers',
            },
        ),
    ]
