# Generated by Django 4.1.5 on 2023-01-13 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='user_lastname',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='lastname'),
        ),
    ]
