# Generated by Django 4.1.5 on 2023-01-14 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_alter_certificate_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='seria',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='seria'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='number',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
