# Generated by Django 4.1.5 on 2023-01-14 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_certificate_user_fathername'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='hours',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='hours'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='teacher',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='teacher'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='number',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='number'),
        ),
    ]
