# Generated by Django 4.1.5 on 2023-01-15 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_certificate_hours_certificate_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='permission',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='worker',
            name='status',
            field=models.CharField(choices=[('null', "Noma'lum"), ('0', 'Admin'), ('1', 'Leader')], default='null', max_length=10, verbose_name='Nomalum'),
        ),
    ]
