# Generated by Django 4.1.5 on 2023-01-15 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_remove_worker_branch_remove_worker_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='email',
        ),
    ]
